#!/usr/bin/env bash

cd $(dirname $0)

if [ $1 == "build" ] 
then
	~/von/manage build
	pip3 install -r requirements.txt
	pip3 install -r requirements.dev.txt
	
	cd django
	python3 -m venv .
	source bin/activate
	pip3 install -r requirements.txt
	
	cd ppbc
	python3 manage.py makemigrations
	python3 manage.py makemigrations backend
	python3 manage.py migrate

	cd frontend
	npm install

elif [ $1 == "start" ]
then ## start docker containers and run django server
	scripts/startapp
	python3 django/ppbc/manage.py runserver


elif [ $1 == "kill" ]
then ## kill all the running docker containers
	containers=($(sudo docker ps -q))
	if [ ${#containers[@]} -gt 0 ]
	then ## if any containers are running, kill them
		sudo docker kill $(sudo docker ps -q)
	fi
else
	echo "invalid argument"
fi
