#!/usr/bin/env bash
PORTS="5001:5001 10001:10001" ./scripts/run_docker -it http 0.0.0.0 10001 \
        -ot http --admin 0.0.0.0 5001 \
        -e "http://172.17.0.1:10001" \
        --genesis-url "http://172.17.0.1:9000/genesis" \
        --seed 00000000000000000000000000000001 \
        --auto-ping-connection \
        --accept-invites \
        --accept-requests \
        --auto-verify-presentation \
        --auto-respond-credential-offer \
        --auto-respond-presentation-request \
        --wallet-name aries \
        --wallet-type indy \
        --wallet-key key \
        --wallet-storage-type postgres_storage \
        --wallet-storage-config '{"url":"172.0.0.5:5432", "max_connections":5, "connection_timeout":10}' \
        --wallet-storage-creds '{"account":"postgres","password":"docker","admin_account":"postgres","admin_password":"docker"}' \
        --wallet-name "holder"
        --label "holder"