#!/usr/bin/env bash
PORTS="$1:$1 $2:$2" $6run_docker -it http 0.0.0.0 $2 \
        -ot http --admin 0.0.0.0 $1 \
        -e "http://172.17.0.1:$2" \
        --genesis-url "http://172.17.0.1:9000/genesis" \
        --seed $3 \
        --auto-ping-connection \
        --accept-invites \
        --accept-requests \
        --auto-verify-presentation \
        --auto-respond-credential-offer \
        --auto-respond-presentation-request \
        --wallet-name aries \
        --wallet-type indy \
        --wallet-key key \
        --wallet-storage-type postgres_storage \
        --wallet-storage-config '{"url":"172.0.0.5:5432", "max_connections":5}' \
        --wallet-storage-creds '{"account":"postgres","password":"docker","admin_account":"postgres","admin_password":"docker"}' \
        --wallet-name "$4"
        --label "$5"